import Head from 'next/head'
import  Image  from 'next/image';

const Header = () => {
    return (
        <>
         <Head>
        <title>Guest House Feedback Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
        </Head>
        <Image src="/banner.jpg" alt="Vercel Logo" width={1800} height={399} />
       </>
    )
}
export default Header